services:
  app:
    build: .
    image: ${DOCKER_USR}/root-team-web:latest
    container_name: root-team-web
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - ./instance:/app/instance
      - ./static/uploads:/app/static/uploads
